### ISSUE TITLE
DS2302A fails on connect under Kubuntu 16.04

### ISSUE THREAD

**Issue by Tamagotono** [Teuniz/DSRemote#4] opened 2016-08-19 08:43 UTC
I have tried with both Network and USB and get the same error when connecting.
" An error occurred while reading settings from device.  File mainwindow.cp line 1693"

Here is the output from the terminal...

tmc_dev write: *IDN?;:SYST:ERR?
tmc_dev write: :CHAN1:BWL?
tmc_dev write: :CHAN1:COUP?
tmc_dev write: :CHAN1:DISP?
tmc_dev write: :CHAN1:IMP?
tmc_dev write: :CHAN1:INV?
tmc_dev write: :CHAN1:OFFS?
tmc_dev write: :CHAN1:PROB?
tmc_dev write: :CHAN1:SCAL?
tmc_dev write: :CHAN1:VERN?
tmc_dev write: :CHAN2:BWL?
tmc_dev write: :CHAN2:COUP?
tmc_dev write: :CHAN2:DISP?
tmc_dev write: :CHAN2:IMP?
tmc_dev write: :CHAN2:INV?
tmc_dev write: :CHAN2:OFFS?
tmc_dev write: :CHAN2:PROB?
tmc_dev write: :CHAN2:SCAL?
tmc_dev write: :CHAN2:VERN?
tmc_dev write: :TIM:OFFS?
tmc_dev write: :TIM:SCAL?
tmc_dev write: :TIM:DEL:ENAB?
tmc_dev write: :TIM:DEL:OFFS?
tmc_dev write: :TIM:DEL:SCAL?
tmc_dev write: :TIM:HREF:MODE?
tmc_dev write: :TIM:HREF:POS?
tmc_dev write: :TIM:MODE?
tmc_dev write: :TIM:VERN?
tmc_dev write: :TRIG:COUP?
tmc_dev write: :TRIG:MODE?
tmc_dev write: :TRIG:EDG:SLOP?
tmc_dev write: :TRIG:EDG:SOUR?
tmc_dev write: :TRIG:EDG:SOUR CHAN1
tmc_dev write: :TRIG:EDG:LEV?
tmc_dev write: :TRIG:EDG:SOUR CHAN2
tmc_dev write: :TRIG:EDG:LEV?
tmc_dev write: :TRIG:EDG:SOUR CHAN1
tmc_dev write: :TRIG:HOLD?
tmc_dev write: :DISP:GRID?
tmc_dev write: :MEAS:COUN:SOUR?
tmc_dev write: :DISP:TYPE?
tmc_dev write: :ACQ:TYPE?
tmc_dev write: :ACQ:AVER?
tmc_dev write: :DISP:GRAD:TIME?
tmc_dev write: :MATH:FFT:SPL?

Is there anything I can do to help get this device supported?

**Comment by Teuniz** [comment] 2016-08-20 09:00
I made some changes. Can you pull again and recompile? Let me know the result.

**Comment by Tamagotono** [comment] 2016-08-20 09:22
That's awesome! Thank you.
I have tested it and it does connect via LAN, but the refresh rate is between 1.3 and 0.6 frames per second with the "Screen update interval" set to 50 mS.

The "curs", "util" and recording buttons do not seem to do anything. It seems to be very close to being fully functional. Yay!

When I try connecting via USB I get "An error occurred while reading screen data from device.  File screen_thread.cpp line 608"

Output from terminal:
tmc_dev write: *IDN?;:SYST:ERR?
tmc_dev write: :CHAN1:BWL?
tmc_dev write: :CHAN1:COUP?
tmc_dev write: :CHAN1:DISP?
tmc_dev write: :CHAN1:IMP?
tmc_dev write: :CHAN1:INV?
tmc_dev write: :CHAN1:OFFS?
tmc_dev write: :CHAN1:PROB?
tmc_dev write: :CHAN1:SCAL?
tmc_dev write: :CHAN1:VERN?
tmc_dev write: :CHAN2:BWL?
tmc_dev write: :CHAN2:COUP?
tmc_dev write: :CHAN2:DISP?
tmc_dev write: :CHAN2:IMP?
tmc_dev write: :CHAN2:INV?
tmc_dev write: :CHAN2:OFFS?
tmc_dev write: :CHAN2:PROB?
tmc_dev write: :CHAN2:SCAL?
tmc_dev write: :CHAN2:VERN?
tmc_dev write: :TIM:OFFS?
tmc_dev write: :TIM:SCAL?
tmc_dev write: :TIM:DEL:ENAB?
tmc_dev write: :TIM:DEL:OFFS?
tmc_dev write: :TIM:DEL:SCAL?
tmc_dev write: :TIM:HREF:MODE?
tmc_dev write: :TIM:HREF:POS?
tmc_dev write: :TIM:MODE?
tmc_dev write: :TIM:VERN?
tmc_dev write: :TRIG:COUP?
tmc_dev write: :TRIG:MODE?
tmc_dev write: :TRIG:EDG:SLOP?
tmc_dev write: :TRIG:EDG:SOUR?
tmc_dev write: :TRIG:EDG:SOUR CHAN1
tmc_dev write: :TRIG:EDG:LEV?
tmc_dev write: :TRIG:EDG:SOUR CHAN2
tmc_dev write: :TRIG:EDG:LEV?
tmc_dev write: :TRIG:EDG:SOUR CHAN1
tmc_dev write: :TRIG:HOLD?
tmc_dev write: :DISP:GRID?
tmc_dev write: :MEAS:COUN:SOUR?
tmc_dev write: :DISP:TYPE?
tmc_dev write: :ACQ:TYPE?
tmc_dev write: :ACQ:AVER?
tmc_dev write: :DISP:GRAD:TIME?
tmc_dev write: :CALC:FFT:SPL?
tmc_dev write: :CALC:MODE?
tmc_dev write: :CALC:FFT:VSM?
tmc_dev write: :CALC:FFT:SOUR?
tmc_dev write: :CALC:FFT:HSP?
tmc_dev write: :CALC:FFT:HCEN?
tmc_dev write: :CALC:FFT:VOFF?
tmc_dev write: :CALC:FFT:VSC?
Can not read from device.

Thanks again, for your help and for making this software in the first place.

**Comment by Teuniz** [comment] 2016-08-20 10:14
The refresh rate is low because the scope's firmware is slow to respond to waveform data requests.
There's nothing that can be done to improve this (apart from Rigol).

The "curs", "util" and recording buttons are (functionally) not implemented (yet).

The USB connection problem seems to be on a very low level. I don't know if I can fix that
without actually having the scope at hand for debugging.
Did you notice a delay/freeze of 5 seconds between "tmc_dev write: :CALC:FFT:VSC?" and "Can not read from device."?

Also, try the following: With DSRemote disconnected, reset the oscilloscope back to the factory settings. Press Sorage -> Default. Then try to connect again.

Have you updated the firmware of your scope to the latest version?
Have a look here: [http://int.rigol.com/Support/SoftDownload/3](http://int.rigol.com/Support/SoftDownload/3)

**Comment by Tamagotono** [comment] 2016-08-20 19:24
Thanks for the quick reply.

There is a freeze of about 2 seconds between "tmc_dev write: :CALC:FFT:VSC?" and "Can not read from device".  I did find that I only get the "Can not read from device." message when one or more channels are enabled. If CH1, CH2 and MATH are all off, I do not get this message.

I reset to factory settings with DSRemote disconnected and there was no change in the error message or the way it failed.

I am running the newest firmware (00.03.04.SP2), I had updated it week ago when I bought the scope.


If you are interested in pursuing this further (I fully understand if you don't), I have a couple of USB packet dumps of the failure.
Here is the dump from the ":WAV:DATA?" until it fails.  https://drive.google.com/open?id=0B_hVYk5JyO0IQXVPakNWU2RQUlE

Here is the full session dump. https://drive.google.com/open?id=0B_hVYk5JyO0IMjRBZDFQdXdrUVU

Hope this helps.

**Comment by Teuniz** [comment] 2016-08-20 20:43
Can you please download the following file: [http://www.teuniz.net/DSRemote/kernel.tar.gz](http://www.teuniz.net/DSRemote/kernel.tar.gz)
Inside you'll find instructions how to patch the usbtmc driver for the "Rigol quirk".
The instructions are valid for Opensuse but will probably work also for Ubuntu.

Let me know the results.

**Comment by Tamagotono** [comment] 2016-08-21 03:45
Well, it took me a bit, but I managed to apply the patch and compile the module. It did not make any difference.

I am now noticing that the delay is less than a second instead of two before, regardless of which module I use. Not sure why the change.

I am happy to continue to troubleshoot this USB issue if you like, but I am quite happy with having access via LAN as well. I will leave it up to you as to whether or not to continue troubleshooting this.

Thanks for all of your help and please feel free to ask me to do any testing/troubleshooting for you with my scope.

**Comment by Teuniz** [comment] 2016-08-21 07:22
One last thing, I noticed that in both files you sent, the last packet is the first half of the screen
waveform data, it has a size of 576 bytes.
When I capture the usb data of my DS1054Z, that packet is followed by another packet with the
rest of the waveform data. I would like to know whether or not your scope is sending the second
packet. Could you do another dump with wireshark and make sure that you stop capturing
packets after the error message appeares and after you closed the DSRemote application?
Because I noticed in the past that sometimes more packets appear in the dump after
closing the application.
(This is due to the fact that wireshark is not a real replacement for a hardware usb analyzer)

**Comment by Tamagotono** [comment] 2016-08-21 07:44
I just tried again and no more packets were sent after closing the
application.

The attached file is the full packet capture. I started WireShark, then
started DSRemote, configured it for USB and selected "Connect". It then
showed the same error as before. I closed the error window, then closed the
application. Once the application had been closed for a minute or two, I
stopped trying to capture packets.

**Comment by tussock-cam** [comment] 2016-08-24 21:56
After the latest commit, my DS2202 seems to do the same as you, @Tamagotono.

I'm currently using Ubuntu in a VirtualBox VM. I've had USB issues with this in the past, so I will try on a native Ubuntu machine later today. Happy to help with debugging, @Teuniz .

**Comment by Teuniz** [comment] 2017-09-22 11:31
The issue seems to be related to https://github.com/Teuniz/DSRemote/issues/12
Closed because the issue is related to a firmware bug in the scope.

**Closed by Teuniz** 2017-09-22 11:31 UTC
